### PR TITLE
Update ConMan to version 3.0.0

### PR DESCRIPTION
**Pull request by naliboff**
Initial pull request update ConMan to version 3.0.0. 

Additional required steps?:
1. Remove unnecessary files (pdfs)
2. Re-test build with different compilers
3. Review documentation
4. ?

@tjesser-ucdavis-edu

### CODE REVIEW

**Comment by tjesser-ucdavis-edu** [comment]
Would it be possible to merge this into a conman3 branch instead of master for now? Jenkins can test multiple branches.

**Comment by naliboff** [comment]
@tjesser-ucdavis-edu Yes, absolutely. As soon as you resubmit the pull request I'll merge it in. If it is easier, I'm happy to add the commits in directly on my end and the update the pull request. Let me know what it is easier for you.

**Comment by tjesser-ucdavis-edu** [comment]
What do you mean by resubmit the pull request? Are you talking about the pull request I made that was already merged or one of the outstanding ones I have open?

**Comment by tjesser-ucdavis-edu** [comment]
It looks like the name of the Makefile changed. If you could add a commit that corrects the Jenkinsfile, that should fix the issue.

**Pull request merged**
