### PR TITLE
Fixes the issue with the pdf having broken links

### PR DESCRIPTION
**Pull request by sdkatvt**
recompiled the manual to fix broken TOC and LOF as well as references and internal links.

### CODE REVIEW

**Comment by sdkatvt** [comment]
I'm not sure if I should open this at this point or what to do next.

**Comment by gassmoeller** [comment]
Opening the pull request was the right step, but I am not sure you included the files that needed to be fixed. It looks like you did not upload a changed .tex file, but would that not be the main file that needs to be updated? I was not aware of any broken links so I am not sure if someone else has more insight into the problem, but the TOC and LOF files are recreated from the .tex files every time the manual is compiled (thus they do not need to be in the repository).
Could you:
- explain what exactly was broken before?
- if you talked to someone about this before who that was to make clear who should take a look at this?

Thanks

**Comment by sdkatvt** [comment]
The pdf file had no toc or lof and ? For references.  It had not been properly recompiled after adding the DOI in the text.  The Tex and bib files were/are fine and did/do not need to change.  Numerous people had been complaining about the broken refs in the pdf.  I agree that it doesn’t seem like a lot to ask people to recompile a latex file but well there you have it. 

I added the extra files that were created when running latex because depending on the flavor of latex you use these apparently don’t always get made. 

Scott

**Comment by gassmoeller** [comment]
Ah thanks, I just now saw the email discussion (had not checked mails this morning). I will let @naliboff handle the further proceedings.

**Pull request closed without merging**
